---
- name: create vpn user
  hosts: pnb
  remote_user: root
  tasks:
    - name: 'Create a directory if it does not exist'
      environment:
        USER_VPN: lab-wesley
      ansible.builtin.file:
        path: /tmp/vpn-$USER_VPN
        state: directory
        mode: '0775'

    - name: 'Create OVPN file'
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.shell: 
        cmd: ./lab_add_client.sh $USER_VPN
        chdir: /etc/openvpn/easy-rsa
      
    - name: 'Create user'
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.shell:
        cmd: useradd -s /sbin/nologin $USER_VPN
      
    - name: 'Define password'
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.shell:
        cmd: PWGEN=$(pwgen -s -1 20) && echo -n $PWGEN | passwd --stdin $USER_VPN && echo "Your username is [ $USER_VPN ] and password [ $PWGEN ]" >> /tmp/vpn-$USER_VPN/$USER_VPN.txt

    - name: 'Configure 2FA Google-Authenticator'
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.shell: 
        cmd: ./google_auth_gen.sh $USER_VPN > /tmp/vpn-$USER_VPN/$USER_VPN-google-authenticator.txt
        chdir: /etc/openvpn/google-authenticator

    - name: 'Copy and change permission user files'
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.shell:
        cmd: cp /etc/openvpn/client/$USER_VPN/$USER_VPN.ovpn /tmp/vpn-$USER_VPN && chmod 775 /tmp/vpn-$USER_VPN/*
    
    - name: Pulling google-authenticator file for my environment
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.fetch:
        src: /tmp/vpn-$USER_VPN/$USER_VPN-google-authenticator.txt
        dest: /tmp/

    - name: Pulling credentials file for my environment 01
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.fetch:
        src: /tmp/vpn-$USER_VPN/$USER_VPN.txt
        dest: /tmp/

    - name: Pulling ovp file for my environment 01
      environment:
        USER_VPN: lab-wesley
      become: true
      ansible.builtin.fetch:
        src: /tmp/vpn-$USER_VPN/$USER_VPN.ovpn
        dest: /tmp/

    