---
- name: create vpn user
  hosts: yyyyy
  vars:
    editvpnuser: xxxxx
  tasks:
    - name: 'Create a directory if it does not exist'
      environment:
        USER_VPN: "{{ editvpnuser }}"
      ansible.builtin.file:
        path: ~/vpn-$USER_VPN
        state: directory
        mode: '0775'

    - name: 'Create OVPN file'
      environment:
        USER_VPN: "{{ editvpnuser }}"
      become: true
      ansible.builtin.shell: 
        cmd: ./lab_add_client.sh $USER_VPN
        chdir: /etc/openvpn/easy-rsa
      
    - name: 'Create user'
      environment:
        USER_VPN: "{{ editvpnuser }}"
      become: true
      ansible.builtin.shell:
        cmd: useradd -s /sbin/nologin $USER_VPN
      
    - name: 'Define password'
      environment:
        USER_VPN: "{{ editvpnuser }}"
      become: true
      ansible.builtin.shell:
        cmd: PWGEN=$(pwgen -s -1 20) && echo -n $PWGEN | passwd --stdin $USER_VPN && echo "Your username is [ $USER_VPN ] and password [ $PWGEN ]" >> /home/$SUDO_USER/vpn-$USER_VPN/$USER_VPN.txt

    - name: 'Configure 2FA Google-Authenticator'
      environment:
        USER_VPN: "{{ editvpnuser }}"
      become: true
      ansible.builtin.shell: 
        cmd: ./google_auth_gen.sh $USER_VPN > /home/$SUDO_USER/vpn-$USER_VPN/$USER_VPN-google-authenticator.txt
        chdir: /etc/openvpn/google-authenticator

    - name: 'Copy and change permission user files'
      environment:
        USER_VPN: "{{ editvpnuser }}"
      become: true
      ansible.builtin.shell:
        cmd: cp /etc/openvpn/client/$USER_VPN/$USER_VPN.ovpn /home/$SUDO_USER/vpn-$USER_VPN/ && chmod 775 /home/$SUDO_USER/vpn-$USER_VPN/*